# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image.proto',
  package='ml',
  syntax='proto3',
  serialized_options=b'Z\003pb/',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bimage.proto\x12\x02ml\"\x1b\n\x0bUpdateInput\x12\x0c\n\x04kind\x18\x01 \x01(\t\"\x18\n\x05Image\x12\x0f\n\x07\x63ontent\x18\x01 \x01(\t27\n\x0cImageService\x12\'\n\tReadImage\x12\x0f.ml.UpdateInput\x1a\t.ml.ImageB\x05Z\x03pb/b\x06proto3'
)




_UPDATEINPUT = _descriptor.Descriptor(
  name='UpdateInput',
  full_name='ml.UpdateInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kind', full_name='ml.UpdateInput.kind', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=46,
)


_IMAGE = _descriptor.Descriptor(
  name='Image',
  full_name='ml.Image',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='content', full_name='ml.Image.content', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=72,
)

DESCRIPTOR.message_types_by_name['UpdateInput'] = _UPDATEINPUT
DESCRIPTOR.message_types_by_name['Image'] = _IMAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UpdateInput = _reflection.GeneratedProtocolMessageType('UpdateInput', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEINPUT,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:ml.UpdateInput)
  })
_sym_db.RegisterMessage(UpdateInput)

Image = _reflection.GeneratedProtocolMessageType('Image', (_message.Message,), {
  'DESCRIPTOR' : _IMAGE,
  '__module__' : 'image_pb2'
  # @@protoc_insertion_point(class_scope:ml.Image)
  })
_sym_db.RegisterMessage(Image)


DESCRIPTOR._options = None

_IMAGESERVICE = _descriptor.ServiceDescriptor(
  name='ImageService',
  full_name='ml.ImageService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=74,
  serialized_end=129,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReadImage',
    full_name='ml.ImageService.ReadImage',
    index=0,
    containing_service=None,
    input_type=_UPDATEINPUT,
    output_type=_IMAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_IMAGESERVICE)

DESCRIPTOR.services_by_name['ImageService'] = _IMAGESERVICE

# @@protoc_insertion_point(module_scope)
